version: 1.0.{build}
image: Visual Studio 2015
install:
# the services: property below doesn't start services at this point so we must
- ps: Start-Service 'MSSQL$SQL2016'
- cmd: sqlcmd -S "%SQL_SERVER_INSTANCE%" -i .\appveyor\init.sql
- ps: $env:SQL_SERVER_BACKUP_DIRECTORY=(Get-ItemProperty "HKLM:\Software\Microsoft\Microsoft SQL Server\MSSQL13.SQL2016\MSSqlServer").BackupDirectory
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  NUGET_RESTORE_VERBOSITY: quiet
  SQL_SERVER_INSTANCE: (local)\SQL2016
  SQL_SERVER_USER: AlwaysEncryptedOwner
  SQL_SERVER_PASSWORD: 7aO!z@xUu!4r6EvD#D&l$sz6&h^rhxL6fzAHMpnOga@LO*WdsEdpfh4^Egtl
  SQL_SERVER_DATABASE: AlwaysEncryptedSample
  matrix:
  - {}
services: 
- mssql2016
before_build:
- cmd: nuget restore -Verbosity %NUGET_RESTORE_VERBOSITY%
build:
  publish_wap: true
  parallel: true
  verbosity: minimal
after_build:
  - ps: .\appveyor\Start-EntityFrameworkMigration.ps1
  - cmd: sqlcmd -S "%SQL_SERVER_INSTANCE%" -Q "BACKUP DATABASE [$(SQL_SERVER_DATABASE)] TO DISK='$(SQL_SERVER_DATABASE).bak' WITH FORMAT, COMPRESSION, STATS=10;"
  - cmd: dir %SQL_SERVER_BACKUP_DIRECTORY%
  - cmd: sqlcmd -S "%SQL_SERVER_INSTANCE%" -i .\appveyor\backup_report.sql
  - ps: Move-Item -Path (Join-Path $env:SQL_SERVER_BACKUP_DIRECTORY "$($env:SQL_SERVER_DATABASE).bak") -Destination $env:APPVEYOR_BUILD_FOLDER -Verbose
  - cmd: git status
  - cmd: set APPVEYOR_BUILD_FOLDER
artifacts:
  - path: $(SQL_SERVER_DATABASE).bak
    name: Database backup
    type: file 