version: 1.0.{build}
image: Visual Studio 2015
install:
- ps: $env:SQL_SERVER_BACKUP_DIRECTORY=(Get-ItemProperty "HKLM:\Software\Microsoft\Microsoft SQL Server\MSSQL13.SQL2016\MSSqlServer").BackupDirectory
assembly_info:
  patch: true
  file: 'GlobalAssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  MSBUILD_LOG_VERSION: 2.0.94
  MSBUILD_LOG_FILE: msbuild.binlog
  NUGET_VERBOSITY: quiet
  SQL_SERVER_INSTANCE: (local)\SQL2016
  SQL_SERVER_USER: AlwaysEncryptedOwner
  SQL_SERVER_PASSWORD: 7aO!z@xUu!4r6EvD#D&l$sz6&h^rhxL6fzAHMpnOga@LO*WdsEdpfh4^Egtl
  SQL_SERVER_DATABASE: AlwaysEncryptedSample
  SQL_SERVER_BLANK_DATABASE: BlankDatabase
  SQL_SERVER_BACKUP_FILE: $(SQL_SERVER_DATABASE).bak
  SQL_SERVER_DACPAC: $(SQL_SERVER_DATABASE).dacpac
  SQL_SERVER_GENERATED_SCHEMA: $(SQL_SERVER_DATABASE).sql
  SQL_SERVER_CONNECTION_STRING: "Data Source=$(SQL_SERVER_INSTANCE);Initial Catalog=$(SQL_SERVER_DATABASE);UID=$(SQL_SERVER_USER);PWD=$(SQL_SERVER_PASSWORD);Application Name=AppVeyor CI Process;Column Encryption Setting=enabled"
  SQL_SERVER_VERIFICATION_LOG: $(SQL_SERVER_DATABASE).verification.log
  matrix:
  - {}
services: 
- mssql2016
nuget:
  # This might be causing a hang.
  # account_feed: true
  project_feed: true
cache:
- packages -> **\packages.config
before_build:
- cmd: sqlcmd -S "%SQL_SERVER_INSTANCE%" -i .\appveyor\init.sql
- cmd: nuget restore -Verbosity %NUGET_VERBOSITY%
- cmd: nuget install MSBuild.StructuredLogger -Version %MSBUILD_LOG_VERSION%  -SolutionDirectory . -Verbosity %NUGET_VERBOSITY%
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  publish_wap: true
  parallel: true
  verbosity: minimal
after_build:
  - ps: .\appveyor\Start-EntityFrameworkMigration.ps1
  - cmd: sqlcmd -S "%SQL_SERVER_INSTANCE%" -d %SQL_SERVER_DATABASE% -W -i .\appveyor\schema_verification.sql -o %SQL_SERVER_VERIFICATION_LOG%
  - cmd: sqlcmd -S "%SQL_SERVER_INSTANCE%" -Q "BACKUP DATABASE [$(SQL_SERVER_DATABASE)] TO DISK='$(SQL_SERVER_BACKUP_FILE)' WITH FORMAT, COMPRESSION, STATS=10;"
  - ps: Move-Item -Path (Join-Path $env:SQL_SERVER_BACKUP_DIRECTORY "$($env:SQL_SERVER_BACKUP_FILE)") -Destination $env:APPVEYOR_BUILD_FOLDER
  - cmd: sqlpackage.exe /Action:Extract /TargetFile:"%SQL_SERVER_DACPAC%" /SourceServerName:"%SQL_SERVER_INSTANCE%" /SourceDatabaseName:%SQL_SERVER_DATABASE%
  - cmd: git status
artifacts:
  - path: $(SQL_SERVER_BACKUP_FILE)
    name: Database backup
    type: file
  - path: $(SQL_SERVER_DACPAC)
    name: DACPAC
    type: file
  - path: $(SQL_SERVER_VERIFICATION_LOG)
    name: Verifiction Query Results
    type: file
  - path: $(MSBUILD_LOG_FILE)
    name: MSBuild BInary Log
    type: file
deploy:
  - provider: NuGet
    api_key:
      secure: xiaaqhkzpM5TJP03w592QTLfxyWs2CBHS0KgDJ35m+Avtp1ARBs7QGjnnxbRnO1/
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      branch: [
        feature/nuget,
        master
      ]
