version: 1.0.{build}
image: Visual Studio 2015
install:
# the services: property below doesn't start services at this point so we must
- ps: Start-Service 'MSSQL$SQL2016'
- cmd: sqlcmd -S "%SQL_SERVER_INSTANCE%" -i .\appveyor\init.sql
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  SQL_SERVER_INSTANCE: (local)\SQL2016
  SQL_SERVER_USER: AlwaysEncryptedOwner
  SQL_SERVER_PASSWORD: 7aO!z@xUu!4r6EvD#D&l$sz6&h^rhxL6fzAHMpnOga@LO*WdsEdpfh4^Egtl
  SQL_SERVER_DATABASE: AlwaysEncryptedSample
  matrix:
  - {}
services: 
- mssql2016
before_build:
- cmd: nuget restore
build:
  publish_wap: true
  parallel: true
  verbosity: minimal
after_build:
  - ps: .\appveyor\Start-EntityFrameworkMigration.ps1
  # BEGIN DEBUG CODE 
  - cmd: sqlcmd -S "%SQL_SERVER_INSTANCE%" -Q "SELECT DB_NAME(database_id), name as [FileName], type_desc, physical_name FROM master.sys.master_files;"
  - ps: ls "HKLM:\Software\Microsoft\Microsoft SQL Server\MSSQL*.*\MSSqlServer"
  # END DEBUG CODE