//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlwaysEncryptedSample.Models.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlwaysEncryptedSample.Models.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF OBJECT_ID(&apos;[Logging].[Log]&apos;) IS NULL
        ///BEGIN
        ///	CREATE TABLE [Logging].[Log] (
        ///		[Id] [int] IDENTITY (1, 1) NOT NULL
        ///			CONSTRAINT PK_Log PRIMARY KEY  CLUSTERED,
        ///		[Date] [datetime] NOT NULL,
        ///		[Thread] [varchar] (255) NOT NULL,
        ///		[Level] [varchar] (50) NOT NULL,
        ///		[Logger] [varchar] (255) NOT NULL,
        ///		[User] [nvarchar] (50) NULL,
        ///		[ClientIP]
        ///		    [nvarchar](45) -- Why 45? Because IPv6 Why Nvarchar? Because Log4Net
        ///		    COLLATE  Latin1_General_BIN2
        ///		    ENCRYPTED WITH (
        ///		        COLUMN_ENCR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Log4NetDDL {
            get {
                return ResourceManager.GetString("Log4NetDDL", resourceCulture);
            }
        }
    }
}
